### ISSUE TITLE
Help with getting as.anndata running

### ISSUE THREAD

**Issue by jjia1** [samuel-marsh/scCustomize#168] opened 2024-03-15 05:54 UTC
Hi Sam,

Thanks so much for making scCustomize. I only recently found the support for file conversion and I think it's really great. I recommend this package to all my labmates. 

I recently was trying to ```as.anndata``` running but I'm running into an error and I was wondering if you could help me debug it. I'm not really sure where the error is coming from. Here's the V5 Seurat object I'm using. 
```
> seurat_obj
An object of class Seurat
43282 features across 74037 samples within 2 assays
Active assay: RNA (22401 features, 5000 variable features)
 3 layers present: counts, data, scale.data
 1 other assay present: unspliced
> Assays(seurat_obj)
[1] "RNA"       "unspliced"
> Layers(seurat_obj)
[1] "counts"     "data"       "scale.data"
```

I ran the as.anndata code and this is the error I'mm getting
```
> as.anndata(seurat_obj, file_path = getwd(), file_name = "mixed_object.h5ad")
• Checking Seurat object validity & Extracting Data
Error in `select()`:
ℹ In argument: `which(single_val_columns)`.
Caused by error in `which()`:
! argument to 'which' is not logical
Run `rlang::last_trace()` to see where the error occurred.
```
And when I run `rlang::last_trace()` I get this output
```
> rlang::last_trace()
<error/rlang_error>
Error in `select()`:
ℹ In argument: `which(single_val_columns)`.
Caused by error in `which()`:
! argument to 'which' is not logical
---
Backtrace:
     ▆
  1. ├─scCustomize::as.anndata(seurat_obj, file_path = getwd(), file_name = "mixed_object.h5ad")
  2. ├─scCustomize:::as.anndata.Seurat(...)
  3. │ └─scCustomize:::drop_single_value_cols(df = x[[assay]]@meta.features)
  4. │   └─df %>% select(which(single_val_columns)) %>% colnames()
  5. ├─base::colnames(.)
  6. │ └─base::is.data.frame(x)
  7. ├─dplyr::select(., which(single_val_columns))
  8. ├─dplyr:::select.data.frame(., which(single_val_columns))
  9. │ └─tidyselect::eval_select(expr(c(...)), data = .data, error_call = error_call)
 10. │   └─tidyselect:::eval_select_impl(...)
 11. │     ├─tidyselect:::with_subscript_errors(...)
 12. │     │ └─base::withCallingHandlers(...)
 13. │     └─tidyselect:::vars_select_eval(...)
 14. │       └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 15. │         └─tidyselect:::eval_c(expr, data_mask, context_mask)
 16. │           └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 17. │             └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
 18. │               └─tidyselect:::eval_context(expr, context_mask, call = error_call)
 19. │                 ├─tidyselect:::with_chained_errors(...)
 20. │                 │ └─base::withCallingHandlers(...)
 21. │                 └─rlang::eval_tidy(as_quosure(expr, env), context_mask)
 22. ├─base::which(single_val_columns)
 23. └─base::which(single_val_columns)
Run rlang::last_trace(drop = FALSE) to see 4 hidden frames.
```

Also here's my sessionInfo. 
```
> sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: America/Chicago
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] sceasy_0.0.7          reticulate_1.35.0     scCustomize_2.1.2
 [4] lubridate_1.9.3       forcats_1.0.0         stringr_1.5.1
 [7] dplyr_1.1.4           purrr_1.0.2           readr_2.1.5
[10] tidyr_1.3.1           tibble_3.2.1          ggplot2_3.5.0
[13] tidyverse_2.0.0       SeuratDisk_0.0.0.9020 Seurat_5.0.2
[16] SeuratObject_5.0.1    sp_2.1-3

loaded via a namespace (and not attached):
  [1] RColorBrewer_1.1-3     shape_1.4.6.1          jsonlite_1.8.8
  [4] magrittr_2.0.3         spatstat.utils_3.0-4   ggbeeswarm_0.7.2
  [7] fs_1.6.2               GlobalOptions_0.1.2    vctrs_0.6.5
 [10] ROCR_1.0-11            memoise_2.0.1          spatstat.explore_3.2-6
 [13] paletteer_1.6.0        janitor_2.2.0          usethis_2.2.3
 [16] htmltools_0.5.7        curl_5.2.1             sctransform_0.4.1
 [19] parallelly_1.37.1      KernSmooth_2.23-22     desc_1.4.3
 [22] htmlwidgets_1.6.4      ica_1.0-3              plyr_1.8.9
 [25] cachem_1.0.8           plotly_4.10.4          zoo_1.8-12
 [28] igraph_2.0.3           mime_0.12              lifecycle_1.0.4
 [31] pkgconfig_2.0.3        Matrix_1.6-5           R6_2.5.1
 [34] fastmap_1.1.1          snakecase_0.11.1       fitdistrplus_1.1-11
 [37] future_1.33.1          shiny_1.8.0            digest_0.6.35
 [40] colorspace_2.1-0       rematch2_2.1.2         ps_1.7.6
 [43] patchwork_1.2.0        tensor_1.5             RSpectra_0.16-1
 [46] irlba_2.3.5.1          pkgload_1.3.4          progressr_0.14.0
 [49] fansi_1.0.6            spatstat.sparse_3.0-3  timechange_0.3.0
 [52] httr_1.4.7             polyclip_1.10-6        abind_1.4-5
 [55] compiler_4.3.1         remotes_2.4.2.1        bit64_4.0.5
 [58] withr_3.0.0            fastDummies_1.7.3      pkgbuild_1.4.3
 [61] MASS_7.3-60.0.1        sessioninfo_1.2.2      rappdirs_0.3.3
 [64] tools_4.3.1            vipor_0.4.7            lmtest_0.9-40
 [67] beeswarm_0.4.0         httpuv_1.6.11          future.apply_1.11.1
 [70] goftest_1.2-3          glue_1.7.0             callr_3.7.5
 [73] nlme_3.1-164           promises_1.2.1         grid_4.3.1
 [76] Rtsne_0.17             cluster_2.1.6          reshape2_1.4.4
 [79] generics_0.1.3         hdf5r_1.3.10           gtable_0.3.4
 [82] spatstat.data_3.0-4    tzdb_0.4.0             data.table_1.15.2
 [85] hms_1.1.3              utf8_1.2.4             spatstat.geom_3.2-9
 [88] RcppAnnoy_0.0.22       ggrepel_0.9.5          RANN_2.6.1
 [91] pillar_1.9.0           ggprism_1.0.4          spam_2.10-0
 [94] RcppHNSW_0.6.0         later_1.3.2            circlize_0.4.16
 [97] splines_4.3.1          lattice_0.22-5         survival_3.5-8
[100] bit_4.0.5              deldir_2.0-4           tidyselect_1.2.1
[103] miniUI_0.1.1.1         pbapply_1.7-2          gridExtra_2.3
[106] scattermore_1.2        devtools_2.4.5         matrixStats_1.2.0
[109] stringi_1.8.3          lazyeval_0.2.2         codetools_0.2-19
[112] cli_3.6.2              uwot_0.1.16            xtable_1.8-4
[115] processx_3.8.3         munsell_0.5.0          Rcpp_1.0.12
[118] globals_0.16.3         spatstat.random_3.2-3  png_0.1-8
[121] ggrastr_1.0.2          parallel_4.3.1         ellipsis_0.3.2
[124] dotCall64_1.1-1        profvis_0.3.8          urlchecker_1.0.1
[127] listenv_0.9.1          viridisLite_0.4.2      scales_1.3.0
[130] fortunes_1.5-4         ggridges_0.5.6         leiden_0.4.3.1
[133] crayon_1.5.2           rlang_1.1.3            cowplot_1.1.3
```

**Comment by samuel-marsh** [comment] 2024-03-15 12:27
Hi @jjia1,

Thanks so much for kind words!  Could you run the following code and paste the output?

```
meta <- Fetch_Meta(OBJ)
head(meta)

dropped <- scCustomize:::drop_single_value_cols(df = meta)
dropped
```

Thanks,
Sam

**Comment by jjia1** [comment] 2024-03-15 16:08
Here's the output

```
> head(meta)
                              orig.ident nCount_RNA nFeature_RNA
NA18-Con-D1_AAACCCACACACTGGC NA18-Con-D1       8915         3437
NA18-Con-D1_AAACCCACACTGGAAG NA18-Con-D1      13101         4183
NA18-Con-D1_AAACCCAGTGGCTCTG NA18-Con-D1       9971         3533
NA18-Con-D1_AAACCCAGTGGTTTGT NA18-Con-D1       8245         3445
NA18-Con-D1_AAACCCAGTTCTCGTC NA18-Con-D1       9868         3619
NA18-Con-D1_AAACCCATCTAGGCCG NA18-Con-D1      15554         4716
                             mitochondrial_fraction ribosomal_fraction label
NA18-Con-D1_AAACCCACACACTGGC             0.02299495         0.11665732  live
NA18-Con-D1_AAACCCACACTGGAAG             0.02778414         0.23570720  live
NA18-Con-D1_AAACCCAGTGGCTCTG             0.01694915         0.09728212  live
NA18-Con-D1_AAACCCAGTGGTTTGT             0.03347483         0.18120073  live
NA18-Con-D1_AAACCCAGTTCTCGTC             0.02614512         0.12545602  live
NA18-Con-D1_AAACCCATCTAGGCCG             0.03561785         0.21267841  live
                             nCount_SCT nFeature_SCT seurat_clusters
NA18-Con-D1_AAACCCACACACTGGC       9037         3426               7
NA18-Con-D1_AAACCCACACTGGAAG      10243         4154               0
NA18-Con-D1_AAACCCAGTGGCTCTG       9718         3525               3
NA18-Con-D1_AAACCCAGTGGTTTGT       8711         3433               5
NA18-Con-D1_AAACCCAGTTCTCGTC       9649         3605               3
NA18-Con-D1_AAACCCATCTAGGCCG      10250         4523               1
                             cell_lineage SCT_snn_res.0.6 celltype
NA18-Con-D1_AAACCCACACACTGGC       Neuron               7       EN
NA18-Con-D1_AAACCCACACTGGAAG PriGlialLine               0      NSC
NA18-Con-D1_AAACCCAGTGGCTCTG       Neuron               3       EN
NA18-Con-D1_AAACCCAGTGGTTTGT PriGlialLine               5      NSC
NA18-Con-D1_AAACCCAGTTCTCGTC       Neuron               3       EN
NA18-Con-D1_AAACCCATCTAGGCCG PriGlialLine               1   DivNSC
                             celltype_highres experiment condition timepoint
NA18-Con-D1_AAACCCACACACTGGC              EN1       NA18       Con        D1
NA18-Con-D1_AAACCCACACTGGAAG              NSC       NA18       Con        D1
NA18-Con-D1_AAACCCAGTGGCTCTG              EN1       NA18       Con        D1
NA18-Con-D1_AAACCCAGTGGTTTGT              NSC       NA18       Con        D1
NA18-Con-D1_AAACCCAGTTCTCGTC              EN1       NA18       Con        D1
NA18-Con-D1_AAACCCATCTAGGCCG           DivNSC       NA18       Con        D1
                             condition_timepoint    cell_group
NA18-Con-D1_AAACCCACACACTGGC              Con-D1     EN_Con-D1
NA18-Con-D1_AAACCCACACTGGAAG              Con-D1    NSC_Con-D1
NA18-Con-D1_AAACCCAGTGGCTCTG              Con-D1     EN_Con-D1
NA18-Con-D1_AAACCCAGTGGTTTGT              Con-D1    NSC_Con-D1
NA18-Con-D1_AAACCCAGTTCTCGTC              Con-D1     EN_Con-D1
NA18-Con-D1_AAACCCATCTAGGCCG              Con-D1 DivNSC_Con-D1
                                      gene_name nCount_unspliced
NA18-Con-D1_AAACCCACACACTGGC ENSG00000160072.20            10453
NA18-Con-D1_AAACCCACACTGGAAG ENSG00000142611.17            15488
NA18-Con-D1_AAACCCAGTGGCTCTG ENSG00000157911.11            11456
NA18-Con-D1_AAACCCAGTGGTTTGT ENSG00000142655.13            11566
NA18-Con-D1_AAACCCAGTTCTCGTC ENSG00000149527.18            11444
NA18-Con-D1_AAACCCATCTAGGCCG ENSG00000171621.14            19088
                             nFeature_unspliced
NA18-Con-D1_AAACCCACACACTGGC               3901
NA18-Con-D1_AAACCCACACTGGAAG               4959
NA18-Con-D1_AAACCCAGTGGCTCTG               4071
NA18-Con-D1_AAACCCAGTGGTTTGT               4259
NA18-Con-D1_AAACCCAGTTCTCGTC               4160
NA18-Con-D1_AAACCCATCTAGGCCG               5586
> dropped <- scCustomize::drop_single_value_cols(df = meta)
Error: 'drop_single_value_cols' is not an exported object from 'namespace:scCustomize'
```

Maybe my version of scCustomize is incorrect? `sessionInfo()` shows it as version 2.1.2

**Comment by samuel-marsh** [comment] 2024-03-15 16:25
Hi,

The version is good but you just need to have 3 colons in the command because it's not function normally accessible in package.

```
dropped <- scCustomize:::drop_single_value_cols(df = meta)
dropped
```

**Comment by samuel-marsh** [comment] 2024-03-15 16:33
If when you run that you get the same error then send me email: samuel.marsh@childrens.harvard.edu and I can provide google drive link to share meta.data df.

Best,
Sam

**Comment by jjia1** [comment] 2024-03-15 17:06
Sorry about that I missed the third colon. Here's the output (it's the same as meta) which I assume means the entire metadata is being dropped.
```
> head(dropped)
                              orig.ident nCount_RNA nFeature_RNA
NA18-Con-D1_AAACCCACACACTGGC NA18-Con-D1       8915         3437
NA18-Con-D1_AAACCCACACTGGAAG NA18-Con-D1      13101         4183
NA18-Con-D1_AAACCCAGTGGCTCTG NA18-Con-D1       9971         3533
NA18-Con-D1_AAACCCAGTGGTTTGT NA18-Con-D1       8245         3445
NA18-Con-D1_AAACCCAGTTCTCGTC NA18-Con-D1       9868         3619
NA18-Con-D1_AAACCCATCTAGGCCG NA18-Con-D1      15554         4716
                             mitochondrial_fraction ribosomal_fraction label
NA18-Con-D1_AAACCCACACACTGGC             0.02299495         0.11665732  live
NA18-Con-D1_AAACCCACACTGGAAG             0.02778414         0.23570720  live
NA18-Con-D1_AAACCCAGTGGCTCTG             0.01694915         0.09728212  live
NA18-Con-D1_AAACCCAGTGGTTTGT             0.03347483         0.18120073  live
NA18-Con-D1_AAACCCAGTTCTCGTC             0.02614512         0.12545602  live
NA18-Con-D1_AAACCCATCTAGGCCG             0.03561785         0.21267841  live
                             nCount_SCT nFeature_SCT seurat_clusters
NA18-Con-D1_AAACCCACACACTGGC       9037         3426               7
NA18-Con-D1_AAACCCACACTGGAAG      10243         4154               0
NA18-Con-D1_AAACCCAGTGGCTCTG       9718         3525               3
NA18-Con-D1_AAACCCAGTGGTTTGT       8711         3433               5
NA18-Con-D1_AAACCCAGTTCTCGTC       9649         3605               3
NA18-Con-D1_AAACCCATCTAGGCCG      10250         4523               1
                             cell_lineage SCT_snn_res.0.6 celltype
NA18-Con-D1_AAACCCACACACTGGC       Neuron               7       EN
NA18-Con-D1_AAACCCACACTGGAAG PriGlialLine               0      NSC
NA18-Con-D1_AAACCCAGTGGCTCTG       Neuron               3       EN
NA18-Con-D1_AAACCCAGTGGTTTGT PriGlialLine               5      NSC
NA18-Con-D1_AAACCCAGTTCTCGTC       Neuron               3       EN
NA18-Con-D1_AAACCCATCTAGGCCG PriGlialLine               1   DivNSC
                             celltype_highres experiment condition timepoint
NA18-Con-D1_AAACCCACACACTGGC              EN1       NA18       Con        D1
NA18-Con-D1_AAACCCACACTGGAAG              NSC       NA18       Con        D1
NA18-Con-D1_AAACCCAGTGGCTCTG              EN1       NA18       Con        D1
NA18-Con-D1_AAACCCAGTGGTTTGT              NSC       NA18       Con        D1
NA18-Con-D1_AAACCCAGTTCTCGTC              EN1       NA18       Con        D1
NA18-Con-D1_AAACCCATCTAGGCCG           DivNSC       NA18       Con        D1
                             condition_timepoint    cell_group
NA18-Con-D1_AAACCCACACACTGGC              Con-D1     EN_Con-D1
NA18-Con-D1_AAACCCACACTGGAAG              Con-D1    NSC_Con-D1
NA18-Con-D1_AAACCCAGTGGCTCTG              Con-D1     EN_Con-D1
NA18-Con-D1_AAACCCAGTGGTTTGT              Con-D1    NSC_Con-D1
NA18-Con-D1_AAACCCAGTTCTCGTC              Con-D1     EN_Con-D1
NA18-Con-D1_AAACCCATCTAGGCCG              Con-D1 DivNSC_Con-D1
                                      gene_name nCount_unspliced
NA18-Con-D1_AAACCCACACACTGGC ENSG00000160072.20            10453
NA18-Con-D1_AAACCCACACTGGAAG ENSG00000142611.17            15488
NA18-Con-D1_AAACCCAGTGGCTCTG ENSG00000157911.11            11456
NA18-Con-D1_AAACCCAGTGGTTTGT ENSG00000142655.13            11566
NA18-Con-D1_AAACCCAGTTCTCGTC ENSG00000149527.18            11444
NA18-Con-D1_AAACCCATCTAGGCCG ENSG00000171621.14            19088
                             nFeature_unspliced
NA18-Con-D1_AAACCCACACACTGGC               3901
NA18-Con-D1_AAACCCACACTGGAAG               4959
NA18-Con-D1_AAACCCAGTGGCTCTG               4071
NA18-Con-D1_AAACCCAGTGGTTTGT               4259
NA18-Con-D1_AAACCCAGTTCTCGTC               4160
NA18-Con-D1_AAACCCATCTAGGCCG               5586
```

**Comment by samuel-marsh** [comment] 2024-03-15 18:06
Ok so that is weird that it's working there.

So let me breakdown the issue and next steps as I can't replicate issue you are getting.

Basically, due to anndata structure, before creating anndata object we remove any meta.data columns (at object and assay level) that just have one value for all cells.

It's these lines:
https://github.com/samuel-marsh/scCustomize/blob/fc7a282af3bef6e1cb816fac3b9229f536159238/R/Object_Conversion.R#L1068-L1077

So the error you are getting is that inside of the `drop_single_value_cols` it is having an error because variable that should be logical (TRUE/FALSE) isn't.

So that means that it's those lines were error must be.  The assay meta.data isn't usually issue because it's always unique but let's try that.

Can you run this and let me know what output is?

```
seurat_var_info <- drop_single_value_cols(df = OBJ[["RNA"]]@meta.data)
```

If that fails we'll move from there.

Thanks!
Sam

**Comment by jjia1** [comment] 2024-03-15 19:22
So I have the SCT assay on my data as well. I wonder if that might have been an issue previously as I never specified the assay. Just ran your code and getting an issue here with the meta.data

```
> seurat_var_info <- scCustomize:::drop_single_value_cols(df = data[["RNA"]]@meta.data)
Error in scCustomize:::drop_single_value_cols(df = data[["RNA"]]@meta.data) : 
  no slot of name "meta.data" for this object of class "Assay"
```
This didn't work but if I change the syntax it works.
```
> seurat_var_info <- scCustomize:::drop_single_value_cols(df = data@meta.data)
> seurat_var_info <- scCustomize:::drop_single_value_cols(df = data@meta.data)
> head(seurat_var_info)
                             nCount_RNA nFeature_RNA  orig.ident
NA18-Con-D1_AAACCCACACACTGGC       8915         3437 NA18-Con-D1
NA18-Con-D1_AAACCCACACTGGAAG      13101         4183 NA18-Con-D1
NA18-Con-D1_AAACCCAGTGGCTCTG       9971         3533 NA18-Con-D1
NA18-Con-D1_AAACCCAGTGGTTTGT       8245         3445 NA18-Con-D1
NA18-Con-D1_AAACCCAGTTCTCGTC       9868         3619 NA18-Con-D1
NA18-Con-D1_AAACCCATCTAGGCCG      15554         4716 NA18-Con-D1
                             mitochondrial_fraction ribosomal_fraction label
NA18-Con-D1_AAACCCACACACTGGC             0.02299495         0.11665732  live
NA18-Con-D1_AAACCCACACTGGAAG             0.02778414         0.23570720  live
NA18-Con-D1_AAACCCAGTGGCTCTG             0.01694915         0.09728212  live
NA18-Con-D1_AAACCCAGTGGTTTGT             0.03347483         0.18120073  live
NA18-Con-D1_AAACCCAGTTCTCGTC             0.02614512         0.12545602  live
NA18-Con-D1_AAACCCATCTAGGCCG             0.03561785         0.21267841  live
                             nCount_SCT nFeature_SCT seurat_clusters
NA18-Con-D1_AAACCCACACACTGGC       9037         3426               7
NA18-Con-D1_AAACCCACACTGGAAG      10243         4154               0
NA18-Con-D1_AAACCCAGTGGCTCTG       9718         3525               3
NA18-Con-D1_AAACCCAGTGGTTTGT       8711         3433               5
NA18-Con-D1_AAACCCAGTTCTCGTC       9649         3605               3
NA18-Con-D1_AAACCCATCTAGGCCG      10250         4523               1
                             cell_lineage SCT_snn_res.0.6 celltype
NA18-Con-D1_AAACCCACACACTGGC       Neuron               7       EN
NA18-Con-D1_AAACCCACACTGGAAG PriGlialLine               0      NSC
NA18-Con-D1_AAACCCAGTGGCTCTG       Neuron               3       EN
NA18-Con-D1_AAACCCAGTGGTTTGT PriGlialLine               5      NSC
NA18-Con-D1_AAACCCAGTTCTCGTC       Neuron               3       EN
NA18-Con-D1_AAACCCATCTAGGCCG PriGlialLine               1   DivNSC
                             celltype_highres experiment condition timepoint
NA18-Con-D1_AAACCCACACACTGGC              EN1       NA18       Con        D1
NA18-Con-D1_AAACCCACACTGGAAG              NSC       NA18       Con        D1
NA18-Con-D1_AAACCCAGTGGCTCTG              EN1       NA18       Con        D1
NA18-Con-D1_AAACCCAGTGGTTTGT              NSC       NA18       Con        D1
NA18-Con-D1_AAACCCAGTTCTCGTC              EN1       NA18       Con        D1
NA18-Con-D1_AAACCCATCTAGGCCG           DivNSC       NA18       Con        D1
                             condition_timepoint    cell_group
NA18-Con-D1_AAACCCACACACTGGC              Con-D1     EN_Con-D1
NA18-Con-D1_AAACCCACACTGGAAG              Con-D1    NSC_Con-D1
NA18-Con-D1_AAACCCAGTGGCTCTG              Con-D1     EN_Con-D1
NA18-Con-D1_AAACCCAGTGGTTTGT              Con-D1    NSC_Con-D1
NA18-Con-D1_AAACCCAGTTCTCGTC              Con-D1     EN_Con-D1
NA18-Con-D1_AAACCCATCTAGGCCG              Con-D1 DivNSC_Con-D1
```

**Comment by samuel-marsh** [comment] 2024-03-15 19:37
ok gotcha so you have a Assay not Assay5.

Just to check what happens when you run this:
```
class(OBJ@assays$RNA)

seurat_var_info <- drop_single_value_cols(df = OBJ[["RNA"]]@meta.features)
```

Best,
Sam

**Comment by jjia1** [comment] 2024-03-15 20:39
I'm pretty sure I am using V5 Seurat, wouldn't that be an Assay5? I thought they would be the same.

```
> class(data@assays$RNA)
[1] "Assay"

attr(,"package")
[1] "SeuratObject"

> packageVersion("Seurat")
[1] ‘5.0.2’
> seurat_var_info <- scCustomize:::drop_single_value_cols(df = data[["RNA"]]@meta.features)
Error in `select()`:
ℹ In argument: `which(single_val_columns)`.
Caused by error in `which()`:
! argument to 'which' is not logical
Run `rlang::last_trace()` to see where the error occurred.

> rlang::last_trace()
<error/rlang_error>
Error in `select()`:
ℹ In argument: `which(single_val_columns)`.
Caused by error in `which()`:
! argument to 'which' is not logical
---
Backtrace:
     ▆
  1. ├─scCustomize:::drop_single_value_cols(df = data[["RNA"]]@meta.features)
  2. │ └─df %>% select(which(single_val_columns)) %>% colnames()
  3. ├─base::colnames(.)
  4. │ └─base::is.data.frame(x)
  5. ├─dplyr::select(., which(single_val_columns))
  6. ├─dplyr:::select.data.frame(., which(single_val_columns))
  7. │ └─tidyselect::eval_select(expr(c(...)), data = .data, error_call = error_call)
  8. │   └─tidyselect:::eval_select_impl(...)
  9. │     ├─tidyselect:::with_subscript_errors(...)
 10. │     │ └─base::withCallingHandlers(...)
 11. │     └─tidyselect:::vars_select_eval(...)
 12. │       └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 13. │         └─tidyselect:::eval_c(expr, data_mask, context_mask)
 14. │           └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 15. │             └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
 16. │               └─tidyselect:::eval_context(expr, context_mask, call = error_call)
 17. │                 ├─tidyselect:::with_chained_errors(...)
 18. │                 │ └─base::withCallingHandlers(...)
 19. │                 └─rlang::eval_tidy(as_quosure(expr, env), context_mask)
 20. ├─base::which(single_val_columns)
 21. └─base::which(single_val_columns)
Run rlang::last_trace(drop = FALSE) to see 4 hidden frames.
```

**Comment by samuel-marsh** [comment] 2024-03-15 20:51
So Seurat 5 can either by Assay5 or Assay depending on the settings.

if object was created prior to Seurat5 then it will remain Assay.  If object is created in Seurat 5 it depends on what settings you use:
```
options(Seurat.object.assay.version = "v5")
```
or v3 if that’s your preference.

ScCustomize also has function `Convert_Assay` to easily switch object between Assay and Assay5 on the fly.

But now we know where the error is coming from.

I’ll work on figuring out fix.

In meantime it should work just fine for Assay5.  So trying running:
```
OBJ <- Convert_Assay](seurat_object = OBJ, convert_to = "V5")
```

And then try running `as.anndata` again.

Best,
Sam

**Comment by samuel-marsh** [comment] 2024-03-15 21:33
On further examination can you paste the output of this command here?

```
head(data[["RNA"]]@meta.features)
```

Thanks!
Sam

**Comment by jjia1** [comment] 2024-03-15 21:38
```
> head(data[["RNA"]]@meta.features)
data frame with 0 columns and 6 rows
```

Oh I see. That's a problem for sure because I am not sure what version Seurat i was using when I generated the object. I want to say it would be version 5 if Seurat V5 has been out since last Fall (around August/September) unless by default they use the V3 assay version. 

I will try converting to V5 as I did convert my object into a V3 assay to get it running scEasy but I lost a lot of information.

**Comment by samuel-marsh** [comment] 2024-03-15 21:50
Hi,

So the problem is not the assay type but that there is  data.frame with 0 columns.  The reason have have no discovered is likely because you did the analysis with SCtransform but then are transferring the RNA assay.  So meta.features dataframe is empty in RNA assay.  I will work on fix for this and update here when live.

As  another point that you may be confusing is that there is difference between Seurat version and Assay structure/version.

Seurat v3/4 uses the Assay structure.
Seurat 5 can use either Assay or Assay5 structure.  

As I mentioned in previous post whether or not Seurat 5 creates objects with Assay or Assay 5 structure depends on what you set using `options` command.  If you load object created with Seurat prior to Seurat 5 it will maintain same structure and hence have assays of type “Assay”.

Seurat5 can still do analysis on Assay object for most functions but some require splitting layers be old way of splitting object.  So unless you have need to split layers then there isn’t huge issue using Assay object.

Best,
Sam

**Comment by jjia1** [comment] 2024-03-15 21:52
Hello Sam,

Thanks for the explanation. I think I understand what you mean now about the Assay structure.

Would a short fix just be to transfer the meta.features dataframe to the RNA assay as well or just scratch the SCT results (I was sort of no-brain-following the tutorial) and follow the traditional LogNormalize pipeline on the RNA assay for Seurat?

Thank you for being so responsive and I appreciate all the help so far.

Best,
Johnathan

**Comment by samuel-marsh** [comment] 2024-03-15 23:44
Hi Johnathan,

Glad I could help!  I have just implemented a fix for this (and 2 other bugs in `as.anndata` from other edge cases) and in my testing it worked with no issues.  If you install the develop branch (v2.1.2.9019 or greater) this should solve your issues without needing to change in between assay types or move any data within the object.

If you still get error after updating to that version please let me know here and I'll reopen the issue.

Best,
Sam

**Closed by samuel-marsh** 2024-03-15 23:44 UTC
Labels: bug, more-info-needed

**Comment by TdzBAS** [comment] 2024-07-19 12:21
Hi @samuel-marsh ,

how can I install the develop branch v2.1.2.9019 ? I am facing the same issue!

Best,
T

**Comment by samuel-marsh** [comment] 2024-07-19 13:04
Hi @TdzBAS,

To install latest dev version please run:

```
devtools::install_github(repo = "samuel-marsh/scCustomize", ref = "release/2.2.0")
```

Best,
Sam
