### ISSUE TITLE
error in Cluster_Highlight_Plot when raster = T

### ISSUE THREAD

**Issue by Eomesodermin** [samuel-marsh/scCustomize#132] opened 2023-10-09 14:24 UTC
Reoccuring error when generating a plot using Cluster_Highlight_Plot() when raster = T

when raster = FALSE this error does not occur. not sure if it impacts other plotting functions 

see below for details 

```r
data("pbmc_small")

Idents(pbmc_small) <- pbmc_small@meta.data$groups


scCustomize::Cluster_Highlight_Plot(pbmc_small, 
                                    cluster_name = "g1", 
                                    highlight_color = "Red", 
                                    background_color = "lightgray", 
                                    pt.size = 0.5, 
                                    raster = F)
```
Error in `geom_scattermore()`:
! Problem while converting geom to grob.
ℹ Error occurred in the 1st layer.
Caused by error in `if (cex != 0) ...`:
! the condition has length > 1

<details>
  <summary> rlang::last_trace() and sessionInfo() output </summary>
  
```r
rlang::last_trace()
```
  
Backtrace:
     ▆
  1. ├─base (local) `<fn>`(x)
  2. └─patchwork:::print.patchwork(x)
  3.   └─patchwork:::build_patchwork(plot, plot$layout$guides %||% "auto")
  4.     └─base::lapply(x$plots, plot_table, guides = guides)
  5.       ├─patchwork (local) FUN(X[[i]], ...)
  6.       └─patchwork:::plot_table.ggplot(X[[i]], ...)
  7.         └─ggplot2::ggplotGrob(x)
  8.           ├─ggplot2::ggplot_gtable(ggplot_build(x))
  9.           └─ggplot2:::ggplot_gtable.ggplot_built(ggplot_build(x))
 10.             └─ggplot2:::by_layer(...)
 11.               ├─rlang::try_fetch(...)
 12.               │ ├─base::tryCatch(...)
 13.               │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 14.               │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 15.               │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 16.               │ └─base::withCallingHandlers(...)
 17.               └─ggplot2 (local) f(l = layers[[i]], d = data[[i]])
 18.                 └─l$draw_geom(d, layout)
 19.                   └─ggplot2 (local) draw_geom(..., self = self)
 20.                     └─self$geom$draw_layer(...)
 21.                       └─ggplot2 (local) draw_layer(..., self = self)
 22.                         └─base::lapply(...)
 23.                           └─ggplot2 (local) FUN(X[[i]], ...)
 24.                             ├─rlang::inject(self$draw_panel(data, panel_params, coord, !!!params))
 25.                             └─self$draw_panel(...)
 26.                               └─scattermore (local) draw_panel(...)
 27.                                 ├─ggplot2:::ggname(...)
 28.                                 │ └─grid::grobName(grob, prefix)
 29.                                 ├─grid::rasterGrob(...)
 30.                                 └─scattermore::scattermore(...)
Run rlang::last_trace(drop = FALSE) to see 5 hidden frames.

```r
sessionInfo()

````

R version 4.2.3 (2023-03-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.0

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Matrix_1.5-4.1             anndata_0.7.5.6            harmony_0.1.1              Rcpp_1.0.11                Nebulosa_1.8.0             patchwork_1.1.3            UCell_2.2.0                useful_1.2.6              
 [9] lubridate_1.9.2            forcats_1.0.0              stringr_1.5.0              purrr_1.0.2                readr_2.1.4                tidyr_1.3.0                tibble_3.2.1               ggplot2_3.4.3             
[17] tidyverse_2.0.0            usefulfunctions_0.0.0.9000 scCustomize_1.1.3          dplyr_1.1.3                SeuratDisk_0.0.0.9020      SeuratObject_4.1.3         Seurat_4.3.0.1             rstudioapi_0.15.0         

loaded via a namespace (and not attached):
  [1] rappdirs_0.3.3              ggprism_1.0.4               scattermore_1.2             R.methodsS3_1.8.2           bit64_4.0.5                 knitr_1.44                  irlba_2.3.5.1              
  [8] DelayedArray_0.24.0         data.table_1.14.8           KEGGREST_1.38.0             RCurl_1.98-1.12             generics_0.1.3              BiocGenerics_0.44.0         org.Mm.eg.db_3.16.0        
 [15] cowplot_1.1.1               RSQLite_2.3.1               shadowtext_0.1.2            RANN_2.6.1                  future_1.33.0               bit_4.0.5                   tzdb_0.4.0                 
 [22] enrichplot_1.18.4           spatstat.data_3.0-1         xml2_1.3.5                  httpuv_1.6.11               assertthat_0.2.1            SummarizedExperiment_1.28.0 viridis_0.6.4              
 [29] xfun_0.40                   hms_1.1.3                   evaluate_0.21               promises_1.2.1              fansi_1.0.4                 progress_1.2.2              caTools_1.18.2             
 [36] dbplyr_2.3.3                igraph_1.5.1                DBI_1.1.3                   htmlwidgets_1.6.2           spatstat.geom_3.2-5         stats4_4.2.3                paletteer_1.5.0            
 [43] ellipsis_0.3.2              ks_1.14.1                   biomaRt_2.54.1              deldir_1.0-9                MatrixGenerics_1.10.0       vctrs_0.6.3                 SingleCellExperiment_1.20.1
 [50] Biobase_2.58.0              ROCR_1.0-11                 abind_1.4-5                 cachem_1.0.8                withr_2.5.0                 ggforce_0.4.1               HDO.db_0.99.1              
 [57] progressr_0.14.0            sctransform_0.4.0           treeio_1.22.0               prettyunits_1.1.1           mclust_6.0.0                goftest_1.2-3               cluster_2.1.4              
 [64] DOSE_3.24.2                 ape_5.7-1                   lazyeval_0.2.2              crayon_1.5.2                hdf5r_1.3.8                 spatstat.explore_3.2-3      labeling_0.4.3             
 [71] pkgconfig_2.0.3             tweenr_2.0.2                GenomeInfoDb_1.34.9         nlme_3.1-163                vipor_0.4.5                 rlang_1.1.1                 globals_0.16.2             
 [78] lifecycle_1.0.3             miniUI_0.1.1.1              downloader_0.4              filelock_1.0.2              extrafontdb_1.0             BiocFileCache_2.6.1         ggrastr_1.0.2              
 [85] polyclip_1.10-4             matrixStats_1.0.0           lmtest_0.9-40               aplot_0.2.1                 zoo_1.8-12                  beeswarm_0.4.0              ggridges_0.5.4             
 [92] GlobalOptions_0.1.2         png_0.1-8                   viridisLite_0.4.2           bitops_1.0-7                gson_0.1.0                  R.oo_1.25.0                 KernSmooth_2.23-22         
 [99] Biostrings_2.66.0           blob_1.2.4                  TCGAbiolinks_2.26.0         shape_1.4.6                 qvalue_2.30.0               parallelly_1.36.0           spatstat.random_3.1-6      
[106] gridGraphics_0.5-1          S4Vectors_0.36.2            scales_1.2.1                memoise_2.0.1               magrittr_2.0.3              plyr_1.8.8                  ica_1.0-3                  
[113] gplots_3.1.3                zlibbioc_1.44.0             scatterpie_0.2.1            compiler_4.2.3              factoextra_1.0.7            ash_1.0-15                  RColorBrewer_1.1-3         
[120] fitdistrplus_1.1-11         snakecase_0.11.1            cli_3.6.1                   XVector_0.38.0              listenv_0.9.0               pbapply_1.7-2               MASS_7.3-60                
[127] tidyselect_1.2.0            stringi_1.7.12              TCGAbiolinksGUI.data_1.18.0 proj4_1.0-13                yaml_2.3.7                  GOSemSim_2.24.0             ggrepel_0.9.3              
[134] grid_4.2.3                  fastmatch_1.1-4             tools_4.2.3                 timechange_0.2.0            future.apply_1.11.0         parallel_4.2.3              circlize_0.4.15            
[141] janitor_2.2.0               gridExtra_2.3               farver_2.1.1                Rtsne_0.16                  ggraph_2.1.0                digest_0.6.33               pracma_2.4.2               
[148] shiny_1.7.5                 GenomicRanges_1.50.2        ggalt_0.4.0                 later_1.3.1                 RcppAnnoy_0.0.21            org.Hs.eg.db_3.16.0         httr_1.4.7                 
[155] AnnotationDbi_1.60.2        colorspace_2.1-0            fs_1.6.3                    rvest_1.0.3                 XML_3.99-0.14               tensor_1.5                  reticulate_1.32.0          
[162] IRanges_2.32.0              splines_4.2.3               yulab.utils_0.1.0           uwot_0.1.16                 tidytree_0.4.5              rematch2_2.1.2              spatstat.utils_3.0-3       
[169] graphlayouts_1.0.1          sp_2.0-0                    ggplotify_0.1.2             plotly_4.10.2               xtable_1.8-4                ggtree_3.6.2                jsonlite_1.8.7             
[176] cgdsr_1.3.0                 tidygraph_1.2.3             sceasy_0.0.7                ggfun_0.1.3                 scico_1.5.0                 R6_2.5.1                    remedy_0.1.0               
[183] pillar_1.9.0                htmltools_0.5.6             mime_0.12                   glue_1.6.2                  fastmap_1.1.1               clusterProfiler_4.6.2       BiocParallel_1.32.6        
[190] BiocNeighbors_1.16.0        codetools_0.2-19            maps_3.4.1                  fgsea_1.24.0                mvtnorm_1.2-3               utf8_1.2.3                  lattice_0.21-8             
[197] spatstat.sparse_3.0-2       curl_5.0.2                  ggbeeswarm_0.7.2            leiden_0.4.3                gtools_3.9.4                Rttf2pt1_1.3.12             GO.db_3.16.0               
[204] survival_3.5-7              rmarkdown_2.25              munsell_0.5.0               GenomeInfoDbData_1.2.9      reshape2_1.4.4              gtable_0.3.4                extrafont_0.19

**Comment by samuel-marsh** [comment] 2023-10-09 14:30
Hi,

Thanks for posting bug.  I’ll take look at it.  Would you mind checking if the same error occurs if you use the “develop_V5” branch (it should be backward compatible to Seurat v4 and doesn’t require installation of Seurat V5).  If the error is same please let me know!

Thanks!
Sam

**Comment by Eomesodermin** [comment] 2023-10-09 15:42
Hi, 

error is the same using the develop_V5 branch

**Comment by samuel-marsh** [comment] 2023-10-09 19:33
Thanks so much for checking!  I’ll dig into it.

**Comment by samuel-marsh** [comment] 2023-10-10 07:52
Hi @Eomesodermin,

So I've confirmed the error is coming from issue in Seurat and not scCustomize and there is actually an open issue in Seurat repo related to it.  I'm going to work on figuring out issue and will submit PR to seurat to fix.  Will update here again when I have more information.

Best,
Sam

**Comment by samuel-marsh** [comment] 2023-10-17 16:18
Hi @Eomesodermin,

I have submitted fix via PR to Seurat repo (https://github.com/satijalab/seurat/pull/7914).  Hopefully this will be incorporated into dev branch shortly and upcoming full release of Seurat5.

I'll update final time here when it is approved.

Best,
Sam

**Comment by samuel-marsh** [comment] 2023-10-24 18:40
Hi @Eomesodermin,

This should be all set in newest version of Seurat dev branch (works for me).  If you have any trouble after updating please let me know and I can reopen issue.

Best,
Sam

**Closed by samuel-marsh** 2023-10-24 18:40 UTC
Labels: bug
