### ISSUE TITLE
When converting from Seurat RDS to anndata h5ad, gene names are lost.

### ISSUE THREAD

**Issue by joshuak94** [samuel-marsh/scCustomize#195] opened 2024-08-07 15:05 UTC
When I convert a Seurat RDS object to h5ad and load the file into a python environment, I see that `object.var_names` is just a list of numbers 1...#_of_genes. Even though in the R environment, if I check `object[["RNA"]]$counts` there are gene names. Is there a way to retain this information?

Thanks!

**Comment by samuel-marsh** [comment] 2024-08-07 15:25
Hi @joshuak94,

Can you provide reproducible example using one of SeuratData datasets?

Best,
Sam

**Comment by joshuak94** [comment] 2024-08-07 15:38
Sure.

Generate h5ad from RDS:
```R
library(Seurat)
library(scCustomize)
library(SeuratData)

InstallData("pbmc3k")
pbmc3k = LoadData("pbmc3k")
rownames(pbmc3k)
as.anndata(x = pbmc3k, file_path = "~/", file_name = "pbmc3k.h5ad", main_layer = "counts", other_layers = NULL)
```

Read h5ad in Python:

```python
import scanpy as sc
pbmc3k = sc.read("/project/MDL_JoshKim_Data/vista_sc_240706/models/scvi/pbmc3k.h5ad")
pbmc3k.var_names
```

Notice in the R script, the rownames function generates the gene names. But in the python code, var_names only generates a numbered list.

**Comment by samuel-marsh** [comment] 2024-08-07 18:33
Hi @joshuak94,

Thanks very much!  I can definitely replicate the issue.  So the genes are not lost (you can plot genes and other python packages can extract expression matrices with gene names from anndata) but looks like that slot isn't being filled correctly and I can work on that.  

So that I make sure it works correctly it what context are you accessing gene names in the way you describe?

Thanks!
Sam

**Comment by joshuak94** [comment] 2024-08-07 18:37
I was running analysis with SCANVI and received the following error at some point:

`ValueError: No reference var names found in query data. Please rerun with return_reference_var_names=True to see reference var names.`

It seems when integrating a query dataset into a reference dataset, the tool internally compares the var_names to make sure the gene sets are equal. In my previous tests, I had both query and reference datasets as RDS files which I then made equal and converted to h5ad. But now I wanted to try it with a different reference dataset which is only available as an h5ad file. Thus the discrepancy with the var_names.

Thanks!!

**Comment by joshuak94** [comment] 2024-08-07 18:45
Quick question. I'm not familiar with the anndata package/objects. You said the gene names aren't lost, could you tell me how I can retreive them so that I can manually set the var_names as a temporary workaround?

Thanks again!

**Comment by joshuak94** [comment] 2024-08-14 13:41
Quick update. I ran the source code for converting from Seurat to h5ad myself, and this seems to have worked fine.
```R
# Functions copied from your source code.
drop_single_value_cols <- function(
    df
) {
  if (!inherits(what = "data.frame", x = df)) {
    cli_abort(message = "{.code df} must of be of class data.frame.")
  }

  single_val_columns <- sapply(df, function(x) {
    length(x = unique(x = x)) == 1
    })

  col_names_single <- df %>%
    select(which(single_val_columns)) %>%
    colnames()

  if (length(x = col_names_single) > 0) {
    cli_inform(message = c("The following columns were removed as they contain identical values for all rows:",
                           "i" = "{.field {col_names_single}}"))
  }

  # filter df
  df_filtered <- df %>%
    select(-(all_of(col_names_single)))

  # return df
  return(df_filtered)
}

Fetch_Meta <- function(
    object
) {
  # Pull meta data
  object_meta <- slot(object = object, name = "meta.data")

  return(object_meta)
}

anndata <- reticulate::import("anndata", convert = FALSE)
seurat_var_info = drop_single_value_cols(df = my_data[["RNA"]]@meta.features)
main_layer_data <- LayerData(object = my_data, assay = "RNA", layer = "counts")

meta_data <- Fetch_Meta(object = my_data)

meta_data <- drop_single_value_cols(df = meta_data)
adata <- anndata$AnnData(
    X = Matrix::t(main_layer_data),
    obs = meta_data,
    var = seurat_var_info
  )

adata$var_names # Check that ENSEMBL gene ids are present.
adata$write("~/my_data.h5ad", compression = "gzip")
```

Then the following works as expected:

```python
import scanpy as sc

my_data_python = sc.read("~/my_data.h5ad")

my_data_python.var_names # Correctly returns ENSEMBL gene ids.
```

**Comment by samuel-marsh** [comment] 2024-08-21 12:40
Ok interesting I’ll have to check out what is going wrong when run as full function then.  Thanks for update and I’ll dig into it.  Will update when I know more.

Best,
Sam

**Comment by Dongjie-orange** [comment] 2024-09-04 09:54
the same bug i met

**Comment by samuel-marsh** [comment] 2024-09-27 16:31
Hi @joshuak94 @Dongjie-orange,

This issue has now been resolved in the release branch.  Please install with:
```
devtools::install_github("samuel-marsh/scCustomize", ref = "release/3.0.0")
```

If issue persists after updating please let me know!

Best,
Sam

**Closed by samuel-marsh** 2024-09-27 16:31 UTC
Labels: bug, Not Working As Intended
