### ISSUE TITLE
Error Merge

### ISSUE THREAD

**Issue by eblchen** [samuel-marsh/scCustomize#187] opened 2024-05-23 16:55 UTC
Cannot merge Seurat object list get the following error:
```
entry.seurat <- Merge_Seurat_List(entry.list)
Error in names(model.list) <- all.levels : 
  attempt to set an attribute on NULL
```
Any pointers would be appreciated :)

**Comment by samuel-marsh** [comment] 2024-05-23 17:01
Can you post the output of `traceback()` after receiving the error?

Best,
Sam

**Comment by eblchen** [comment] 2024-05-24 08:32
Sure, thanks for helping with this!
```
> entry.seurat <- Merge_Seurat_List(entry.list)
Error in names(model.list) <- all.levels : 
  attempt to set an attribute on NULL
> traceback()
8: merge.SCTAssay(x = objects[[idx.x]][[assay]], y = lapply(X = objects[idx.y], 
       FUN = "[[", assay), labels = projects, add.cell.ids = NULL, 
       collapse = collapse, merge.data = merge.data)
7: merge(x = objects[[idx.x]][[assay]], y = lapply(X = objects[idx.y], 
       FUN = "[[", assay), labels = projects, add.cell.ids = NULL, 
       collapse = collapse, merge.data = merge.data)
6: merge.Seurat(x = x, y = y, merge.data = merge.data, project = project)
5: merge(x = x, y = y, merge.data = merge.data, project = project)
4: fn(out, elt, ...)
3: reduce_impl(.x, .f, ..., .init = .init, .dir = .dir)
2: reduce(list_seurat, function(x, y) {
       merge(x = x, y = y, merge.data = merge.data, project = project)
   })
1: Merge_Seurat_List(entry.list)
> 
```

**Comment by samuel-marsh** [comment] 2024-05-25 13:37
ok thanks.

What happens if you run:

```
merged <- merge(entry.list[[1]], entry.list[[2:length(x = entry.list)]])
```

Best,
Sam

**Comment by eblchen** [comment] 2024-05-30 15:27
Thanks for following up on this! Sorry haven’t had a chance to check am away at the moment, will get back to you once I've run it :)

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by eblchen** [comment] 2024-05-31 13:30
Hi Sam,
Sorry it's taken a while to reply have been away! This was the result: 
```
> merged <- merge(entry.list[[1]], entry.list[[2:length(x = entry.list)]])
Error in (function (cond)  : 
  error in evaluating the argument 'y' in selecting a method for function 'merge': subscript out of bounds
```

**Comment by samuel-marsh** [comment] 2024-06-06 14:40
Hi @eblchen,

No worries if you haven't had time but just following up on my previous post.

Best,
Sam

**Comment by eblchen** [comment] 2024-06-17 10:02
Hi Sam,
Sorry only just got back from travelling!
```
> merged <- merge(entry.list[[1]], entry.list[2:length(x = entry.list)])
Error in names(model.list) <- all.levels : 
  attempt to set an attribute on NULL
```
This was the error. Thanks for your help with this!

**Comment by samuel-marsh** [comment] 2024-07-03 11:52
Hi @eblchen,

So sorry I've been in and out as well.  So this tells me that the issue is coming from Seurat objects and not scCustomize.  How many objects are in your list? 

Best,
Sam

**Comment by samuel-marsh** [comment] 2024-08-22 12:20
Hi @eblchen 

Just checking in to see if this is still an issue or if I can close the issue?

Thanks!!
Sam

**Comment by eblchen** [comment] 2024-08-22 16:11
Hi Sam,
Don’t think I solved it but found a workaround for now so happy to close the ticket sorry for not getting back to you sooner and thank you for all your help!
Best wishes,
Emilia

Emilia Chen | PhD Student

The Institute of Cancer Research | 15 Cotswold Road, Sutton, SM2 5NG
T +442034376259 | E ***@***.******@***.***> | W www.icr.ac.uk<http://www.icr.ac.uk/> | Twitter @ICR_London<https://twitter.com/ICR_London>
Facebook www.facebook.com/theinstituteofcancerresearch<http://www.facebook.com/theinstituteofcancerresearch>

Making the discoveries that defeat cancer

[ICR Logo]<http://www.icr.ac.uk/>

**Closed** 2024-08-25 18:58 UTC
