### ISSUE TITLE
Clustered_DotPlot Error: number of cluster centres must lie between 1 and nrow(x)

### ISSUE THREAD

**Issue by crazyhottommy** [samuel-marsh/scCustomize#19] opened 2022-01-03 21:52 UTC
Hi, 
I installed the version from dev branch

```r
Clustered_DotPlot(seurat_object = GBM_myeloid_obj, features = unique(myeloid_features), k = 5)
```

Error: number of cluster centres must lie between 1 and nrow(x)

<details>

 I guess the k-means has some problem here. Maybe better to have an option to skip k-means.

Thanks again for making this!
 
```r
> devtools::session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.1.1 (2021-08-10)
 os       Ubuntu 20.04.3 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Etc/UTC                     
 date     2022-01-03                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package              * version    date       lib source                                   
 abind                  1.4-5      2016-07-21 [2] RSPM (R 4.1.0)                           
 assertthat             0.2.1      2019-03-21 [2] RSPM (R 4.1.0)                           
 backports              1.2.1      2020-12-09 [2] RSPM (R 4.1.0)                           
 beeswarm               0.4.0      2021-06-01 [1] RSPM (R 4.1.0)                           
 Biobase                2.52.0     2021-05-19 [1] Bioconductor                             
 BiocGenerics           0.38.0     2021-05-19 [1] Bioconductor                             
 bitops                 1.0-7      2021-04-24 [2] RSPM (R 4.1.0)                           
 broom                  0.7.9      2021-07-27 [2] RSPM (R 4.1.0)                           
 cachem                 1.0.6      2021-08-19 [2] RSPM (R 4.1.0)                           
 Cairo                  1.5-12.2   2020-07-07 [1] RSPM (R 4.1.1)                           
 callr                  3.7.0      2021-04-20 [2] RSPM (R 4.1.0)                           
 car                    3.0-12     2021-11-06 [1] RSPM (R 4.1.0)                           
 carData                3.0-4      2020-05-22 [1] RSPM (R 4.1.0)                           
 cellranger             1.1.0      2016-07-27 [2] RSPM (R 4.1.0)                           
 circlize               0.4.13     2021-06-09 [1] RSPM (R 4.1.0)                           
 cli                    3.0.1      2021-07-17 [2] RSPM (R 4.1.0)                           
 clue                   0.3-60     2021-10-11 [1] RSPM (R 4.1.0)                           
 cluster                2.1.2      2021-04-17 [3] CRAN (R 4.1.1)                           
 codetools              0.2-18     2020-11-04 [3] CRAN (R 4.1.1)                           
 colorspace             2.0-2      2021-06-24 [2] RSPM (R 4.1.0)                           
 colorway               0.2.0      2021-11-19 [1] Github (hypercompetent/colorway@8ba8f00) 
 ComplexHeatmap         2.8.0      2021-05-19 [1] Bioconductor                             
 cowplot                1.1.1      2020-12-30 [2] RSPM (R 4.1.0)                           
 crayon                 1.4.1      2021-02-08 [2] RSPM (R 4.1.0)                           
 curl                   4.3.2      2021-06-23 [2] RSPM (R 4.1.0)                           
 data.table             1.14.2     2021-09-27 [2] RSPM (R 4.1.0)                           
 DBI                    1.1.1      2021-01-15 [2] RSPM (R 4.1.0)                           
 dbplyr                 2.1.1      2021-04-06 [2] RSPM (R 4.1.0)                           
 DelayedArray           0.18.0     2021-05-19 [1] Bioconductor                             
 deldir                 0.2-10     2021-02-16 [2] RSPM (R 4.1.0)                           
 desc                   1.3.0      2021-03-05 [2] RSPM (R 4.1.0)                           
 devtools               2.4.2      2021-06-07 [2] RSPM (R 4.1.0)                           
 digest                 0.6.28     2021-09-23 [2] RSPM (R 4.1.0)                           
 distributional         0.2.2      2021-02-02 [1] RSPM (R 4.1.0)                           
 dittoSeq               1.7.0      2021-11-19 [1] Github (dtm2451/dittoSeq@b158b29)        
 doParallel             1.0.16     2020-10-16 [1] RSPM (R 4.1.0)                           
 dplyr                * 1.0.7      2021-06-18 [2] RSPM (R 4.1.0)                           
 ellipsis               0.3.2      2021-04-29 [2] RSPM (R 4.1.0)                           
 evaluate               0.14       2019-05-28 [2] RSPM (R 4.1.0)                           
 fansi                  0.5.0      2021-05-25 [2] RSPM (R 4.1.0)                           
 farver                 2.1.0      2021-02-28 [2] RSPM (R 4.1.0)                           
 fastmap                1.1.0      2021-01-25 [2] RSPM (R 4.1.0)                           
 fitdistrplus           1.1-5      2021-05-28 [2] RSPM (R 4.1.0)                           
 forcats              * 0.5.1      2021-01-27 [2] RSPM (R 4.1.0)                           
 foreach                1.5.1      2020-10-15 [1] RSPM (R 4.1.0)                           
 fs                     1.5.0      2020-07-31 [2] RSPM (R 4.1.0)                           
 future                 1.22.1     2021-08-25 [2] RSPM (R 4.1.0)                           
 future.apply           1.8.1      2021-08-10 [2] RSPM (R 4.1.0)                           
 generics               0.1.0      2020-10-31 [2] RSPM (R 4.1.0)                           
 GenomeInfoDb           1.28.4     2021-09-05 [1] Bioconductor                             
 GenomeInfoDbData       1.2.6      2021-11-19 [1] Bioconductor                             
 GenomicRanges          1.44.0     2021-05-19 [1] Bioconductor                             
 GetoptLong             1.0.5      2020-12-15 [1] RSPM (R 4.1.0)                           
 ggbeeswarm             0.6.0      2017-08-07 [1] RSPM (R 4.1.0)                           
 ggdist                 3.0.1      2021-11-30 [1] RSPM (R 4.1.0)                           
 ggplot2              * 3.3.5      2021-06-25 [2] RSPM (R 4.1.0)                           
 ggprism                1.0.3.9000 2021-11-19 [1] Github (csdaw/ggprism@e21c3ee)           
 ggpubr                 0.4.0      2020-06-27 [1] RSPM (R 4.1.0)                           
 ggrastr                1.0.1      2021-12-08 [1] RSPM (R 4.1.1)                           
 ggrepel                0.9.1      2021-01-15 [2] RSPM (R 4.1.0)                           
 ggridges               0.5.3      2021-01-08 [2] RSPM (R 4.1.0)                           
 ggsignif               0.6.3      2021-09-09 [1] RSPM (R 4.1.0)                           
 GlobalOptions          0.1.2      2020-06-10 [1] RSPM (R 4.1.0)                           
 globals                0.14.0     2020-11-22 [2] RSPM (R 4.1.0)                           
 glue                   1.4.2      2020-08-27 [2] RSPM (R 4.1.0)                           
 goftest                1.2-2      2019-12-02 [2] RSPM (R 4.1.0)                           
 gridExtra              2.3        2017-09-09 [2] RSPM (R 4.1.0)                           
 gtable                 0.3.0      2019-03-25 [2] RSPM (R 4.1.0)                           
 harmony              * 0.1.0      2021-06-02 [1] RSPM (R 4.1.0)                           
 haven                  2.4.3      2021-08-04 [2] RSPM (R 4.1.0)                           
 here                 * 1.0.1      2020-12-13 [2] RSPM (R 4.1.0)                           
 hms                    1.1.1      2021-09-26 [2] RSPM (R 4.1.0)                           
 htmltools              0.5.2      2021-08-25 [2] RSPM (R 4.1.0)                           
 htmlwidgets            1.5.4      2021-09-08 [2] RSPM (R 4.1.0)                           
 httpuv                 1.6.3      2021-09-09 [2] RSPM (R 4.1.0)                           
 httr                   1.4.2      2020-07-20 [2] RSPM (R 4.1.0)                           
 ica                    1.0-2      2018-05-24 [2] RSPM (R 4.1.0)                           
 igraph                 1.2.6      2020-10-06 [2] RSPM (R 4.1.0)                           
 IRanges                2.26.0     2021-05-19 [1] Bioconductor                             
 irlba                  2.3.3      2019-02-05 [2] RSPM (R 4.1.0)                           
 iterators              1.0.13     2020-10-15 [1] RSPM (R 4.1.0)                           
 janitor                2.1.0      2021-01-05 [1] RSPM (R 4.1.0)                           
 jsonlite               1.7.2      2020-12-09 [2] RSPM (R 4.1.0)                           
 KernSmooth             2.23-20    2021-05-03 [3] CRAN (R 4.1.1)                           
 knitr                  1.34       2021-09-09 [2] RSPM (R 4.1.0)                           
 labeling               0.4.2      2020-10-20 [2] RSPM (R 4.1.0)                           
 later                  1.3.0      2021-08-18 [2] RSPM (R 4.1.0)                           
 lattice                0.20-45    2021-09-22 [3] RSPM (R 4.1.0)                           
 lazyeval               0.2.2      2019-03-15 [2] RSPM (R 4.1.0)                           
 leiden                 0.3.9      2021-07-27 [2] RSPM (R 4.1.0)                           
 lifecycle              1.0.1      2021-09-24 [2] RSPM (R 4.1.0)                           
 listenv                0.8.0      2019-12-05 [2] RSPM (R 4.1.0)                           
 lmtest                 0.9-38     2020-09-09 [2] RSPM (R 4.1.0)                           
 lubridate              1.7.10     2021-02-26 [2] RSPM (R 4.1.0)                           
 magrittr               2.0.1      2020-11-17 [2] RSPM (R 4.1.0)                           
 MASS                   7.3-54     2021-05-03 [3] CRAN (R 4.1.1)                           
 Matrix                 1.3-4      2021-06-01 [3] CRAN (R 4.1.1)                           
 MatrixGenerics         1.4.3      2021-08-26 [1] Bioconductor                             
 matrixStats            0.61.0     2021-09-17 [2] RSPM (R 4.1.0)                           
 memoise                2.0.0      2021-01-26 [2] RSPM (R 4.1.0)                           
 mgcv                   1.8-37     2021-09-23 [3] RSPM (R 4.1.0)                           
 mime                   0.11       2021-06-23 [2] RSPM (R 4.1.0)                           
 miniUI                 0.1.1.1    2018-05-18 [2] RSPM (R 4.1.0)                           
 modelr                 0.1.8      2020-05-19 [2] RSPM (R 4.1.0)                           
 munsell                0.5.0      2018-06-12 [2] RSPM (R 4.1.0)                           
 nlme                   3.1-153    2021-09-07 [3] RSPM (R 4.1.0)                           
 paletteer              1.4.0      2021-07-20 [1] RSPM (R 4.1.0)                           
 parallelly             1.28.1     2021-09-09 [2] RSPM (R 4.1.0)                           
 patchwork              1.1.1      2020-12-17 [2] RSPM (R 4.1.0)                           
 pbapply                1.5-0      2021-09-16 [2] RSPM (R 4.1.0)                           
 pheatmap               1.0.12     2019-01-04 [1] RSPM (R 4.1.0)                           
 pillar                 1.6.3      2021-09-26 [2] RSPM (R 4.1.0)                           
 pkgbuild               1.2.0      2020-12-15 [2] RSPM (R 4.1.0)                           
 pkgconfig              2.0.3      2019-09-22 [2] RSPM (R 4.1.0)                           
 pkgload                1.2.2      2021-09-11 [2] RSPM (R 4.1.0)                           
 plotly                 4.9.4.1    2021-06-18 [2] RSPM (R 4.1.0)                           
 plyr                   1.8.6      2020-03-03 [2] RSPM (R 4.1.0)                           
 png                    0.1-7      2013-12-03 [2] RSPM (R 4.1.0)                           
 Polychrome             1.3.1      2021-07-16 [1] RSPM (R 4.1.0)                           
 polyclip               1.10-0     2019-03-14 [2] RSPM (R 4.1.0)                           
 prettyunits            1.1.1      2020-01-24 [2] RSPM (R 4.1.0)                           
 prismatic              1.1.0      2021-10-17 [1] RSPM (R 4.1.0)                           
 processx               3.5.2      2021-04-30 [2] RSPM (R 4.1.0)                           
 promises               1.2.0.1    2021-02-11 [2] RSPM (R 4.1.0)                           
 ps                     1.6.0      2021-02-28 [2] RSPM (R 4.1.0)                           
 purrr                * 0.3.4      2020-04-17 [2] RSPM (R 4.1.0)                           
 R6                     2.5.1      2021-08-19 [2] RSPM (R 4.1.0)                           
 RANN                   2.6.1      2019-01-08 [2] RSPM (R 4.1.0)                           
 RColorBrewer           1.1-2      2014-12-07 [2] RSPM (R 4.1.0)                           
 Rcpp                 * 1.0.7      2021-07-07 [2] RSPM (R 4.1.0)                           
 RcppAnnoy              0.0.19     2021-07-30 [2] RSPM (R 4.1.0)                           
 RCurl                  1.98-1.5   2021-09-17 [1] RSPM (R 4.1.0)                           
 readr                * 2.0.2      2021-09-27 [2] RSPM (R 4.1.0)                           
 readxl                 1.3.1      2019-03-13 [2] RSPM (R 4.1.0)                           
 rematch2               2.1.2      2020-05-01 [2] RSPM (R 4.1.0)                           
 remotes                2.4.0      2021-06-02 [2] RSPM (R 4.1.0)                           
 reprex                 2.0.1      2021-08-05 [2] RSPM (R 4.1.0)                           
 reshape2               1.4.4      2020-04-09 [2] RSPM (R 4.1.0)                           
 reticulate             1.22       2021-09-17 [2] RSPM (R 4.1.0)                           
 rjson                  0.2.20     2018-06-08 [1] RSPM (R 4.1.0)                           
 rlang                  0.4.11     2021-04-30 [2] RSPM (R 4.1.0)                           
 rmarkdown              2.11       2021-09-14 [2] RSPM (R 4.1.0)                           
 ROCR                   1.0-11     2020-05-02 [2] RSPM (R 4.1.0)                           
 rpart                  4.1-15     2019-04-12 [3] CRAN (R 4.1.1)                           
 rprojroot              2.0.2      2020-11-15 [2] RSPM (R 4.1.0)                           
 rstatix                0.7.0      2021-02-13 [1] RSPM (R 4.1.0)                           
 rstudioapi             0.13       2020-11-12 [2] RSPM (R 4.1.0)                           
 Rtsne                  0.15       2018-11-10 [2] RSPM (R 4.1.0)                           
 rvest                  1.0.1      2021-07-26 [2] RSPM (R 4.1.0)                           
 S4Vectors              0.30.2     2021-10-03 [1] Bioconductor                             
 scales                 1.1.1      2020-05-11 [2] RSPM (R 4.1.0)                           
 scattermore            0.7        2020-11-24 [2] RSPM (R 4.1.0)                           
 scatterplot3d          0.3-41     2018-03-14 [1] RSPM (R 4.1.0)                           
 scCustomize          * 0.6.3.0010 2022-01-03 [1] Github (samuel-marsh/scCustomize@2749725)
 sctransform            0.3.2      2020-12-16 [2] RSPM (R 4.1.0)                           
 sessioninfo            1.1.1      2018-11-05 [2] RSPM (R 4.1.0)                           
 Seurat               * 4.0.6      2021-12-16 [1] RSPM (R 4.1.0)                           
 SeuratObject         * 4.0.4      2021-11-23 [1] RSPM (R 4.1.0)                           
 shape                  1.4.6      2021-05-19 [1] RSPM (R 4.1.0)                           
 shiny                  1.7.0      2021-09-22 [2] RSPM (R 4.1.0)                           
 SingleCellExperiment   1.14.1     2021-05-21 [1] Bioconductor                             
 snakecase              0.11.0     2019-05-25 [1] RSPM (R 4.1.0)                           
 spatstat.core          2.3-0      2021-07-16 [2] RSPM (R 4.1.0)                           
 spatstat.data          2.1-0      2021-03-21 [2] RSPM (R 4.1.0)                           
 spatstat.geom          2.2-2      2021-07-12 [2] RSPM (R 4.1.0)                           
 spatstat.sparse        2.0-0      2021-03-16 [2] RSPM (R 4.1.0)                           
 spatstat.utils         2.2-0      2021-06-14 [2] RSPM (R 4.1.0)                           
 stringi                1.7.4      2021-08-25 [2] RSPM (R 4.1.0)                           
 stringr              * 1.4.0      2019-02-10 [2] RSPM (R 4.1.0)                           
 SummarizedExperiment   1.22.0     2021-05-19 [1] Bioconductor                             
 survival               3.2-13     2021-08-24 [3] RSPM (R 4.1.0)                           
 tensor                 1.5        2012-05-05 [2] RSPM (R 4.1.0)                           
 testthat               3.0.4      2021-07-01 [2] RSPM (R 4.1.0)                           
 tibble               * 3.1.4      2021-08-25 [2] RSPM (R 4.1.0)                           
 tidyr                * 1.1.4      2021-09-27 [2] RSPM (R 4.1.0)                           
 tidyselect             1.1.1      2021-04-30 [2] RSPM (R 4.1.0)                           
 tidyverse            * 1.3.1      2021-04-15 [2] RSPM (R 4.1.0)                           
 tzdb                   0.1.2      2021-07-20 [2] RSPM (R 4.1.0)                           
 usethis                2.0.1      2021-02-10 [2] RSPM (R 4.1.0)                           
 utf8                   1.2.2      2021-07-24 [2] RSPM (R 4.1.0)                           
 uwot                   0.1.10     2020-12-15 [2] RSPM (R 4.1.0)                           
 vctrs                  0.3.8      2021-04-29 [2] RSPM (R 4.1.0)                           
 vipor                  0.4.5      2017-03-22 [1] RSPM (R 4.1.0)                           
 viridis                0.6.2      2021-10-13 [1] RSPM (R 4.1.0)                           
 viridisLite            0.4.0      2021-04-13 [2] RSPM (R 4.1.0)                           
 withr                  2.4.2      2021-04-18 [2] RSPM (R 4.1.0)                           
 xfun                   0.26       2021-09-14 [2] RSPM (R 4.1.0)                           
 xml2                   1.3.2      2020-04-23 [2] RSPM (R 4.1.0)                           
 xtable                 1.8-4      2019-04-21 [2] RSPM (R 4.1.0)                           
 XVector                0.32.0     2021-05-19 [1] Bioconductor                             
 yaml                   2.2.1      2020-02-01 [2] RSPM (R 4.1.0)                           
 zlibbioc               1.38.0     2021-05-19 [1] Bioconductor                             
 zoo                    1.8-9      2021-03-09 [2] RSPM (R 4.1.0)                           

[1] /home/rstudio/R/x86_64-pc-linux-gnu-library/4.1-3.13
[2] /usr/local/lib/R/site-library
[3] /usr/local/lib/R/library
```

**Comment by samuel-marsh** [comment] 2022-01-03 22:05
@crazyhottommy standby let me check it out.  I ran into this error when I was testing function but need to check how I solved it.  If you use SeuratData pbmc3k object (and similar code otherwise) does it through same error?

Thanks!
Sam

**Comment by crazyhottommy** [comment] 2022-01-04 03:16
Hi @samuel-marsh ,
I just tried:

```r
library(SeuratData)
InstallData("pbmc3k")

pbmc3k<- pbmc3k %>%
  NormalizeData(normalization.method = "LogNormalize", scale.factor = 10000) %>%
  FindVariableFeatures( selection.method = "vst", nfeatures = 2000) %>%
  ScaleData() %>%
  RunPCA() %>%
  RunUMAP(reduction = "pca", dims = 1:30) %>%
  FindNeighbors(reduction = "pca", dims = 1:30) %>% 
  FindClusters(resolution = 0.8)
  
  
Clustered_DotPlot(seurat_object = pbmc3k, features = c("IL1B", "CD14", "FCGR3A", "CD4", "CD8A", "CD3D"), k = 5)

```

Same Error: number of cluster centres must lie between 1 and nrow(x)

**Comment by samuel-marsh** [comment] 2022-01-04 13:34
@crazyhottommy Perfect thanks for reprex!!  

So narrowed it down and issue is actually with my k means elbow plot part of the function and not the k-means in dotplot itself, there are two temp solutions and description of the issue below.

Have also discovered an independent issue with color scale not setting properly at default values so working on fix for that as well.  Adding both of these to my to do list in #18.  Full explanation and solutions below.

Will update here when fixed.

**k-means Elbow Plot Issue: `(Error: number of cluster centres must lie between 1 and nrow(x))`**
Again I've narrowed this down to my kmeans elbow plot function as when I run the following the dotplot works just fine:
```
Clustered_DotPlot(seurat_object = pbmc, features = c("IL1B", "CD14", "FCGR3A", "CD4", "CD8A", "CD3D"), k = 5, plot_km_elbow = F)
```

The issue is due to the fact that I set a large value for the `elbow_kmax` parameter so that when it's plotted users get accurate idea of the shape of curve so that they can make accurate choice of elbow/k for the dotplot.  By default the parameter is set to 20 but when gene list is smaller than that it causes issues.  Adjusting this value dependent on gene list will allow for plotting of the elbow.

```
library(tidyverse)
library(Seurat)
library(scCustomize)

pbmc <- pbmc3k.SeuratData::pbmc3k.final
pbmc <- UpdateSeuratObject(pbmc)

markers <- FindAllMarkers(pbmc)

# Works (81 genes) Default Settings
top10_unique <- Extract_Top_Markers(marker_dataframe = markers, named_vector = F, num_genes = 10, make_unique = T)

Clustered_DotPlot(seurat_object = pbmc, features = top10_unique, k = 5)

# Fails (18 genes) Default Settings
top2_unique <- Extract_Top_Markers(marker_dataframe = markers, named_vector = F, num_genes = 2, make_unique = T)

Clustered_DotPlot(seurat_object = pbmc, features = top2_unique, k = 5)

# Works (Modify elbow_kmax)
top2_unique <- Extract_Top_Markers(marker_dataframe = markers, named_vector = F, num_genes = 2, make_unique = T)

Clustered_DotPlot(seurat_object = pbmc, features = top2_unique, k = 5, elbow_kmax = 17)
```

Same is true of modifying `elbow_kmax` in reprex you provided:
```
Clustered_DotPlot(seurat_object = pbmc, features = c("IL1B", "CD14", "FCGR3A", "CD4", "CD8A", "CD3D"), k = 5, plot_km_elbow = T, elbow_kmax = 5)
```

I will add an additional check to set that parameter dynamically dependent on the size of the input gene list.


**SOLUTION (for now):** You can either set `elbow_kmax = (length(GENE_LIST)-1)` or set `plot_km_elbow = FALSE`.

**NEW ISSUE: Color scale not setting properly**

Also in process of this have discovered there is bug in the color scale not setting properly at default values.  Should be -2.5 and 2.5 but you can see scale is running -4 to 4 here:
![image](https://user-images.githubusercontent.com/38284410/148064500-265c6e2c-976f-4beb-af4c-ffa2b3989edc.png)

But when changing to this it works properly:
```
Clustered_DotPlot(seurat_object = pbmc, features = c("IL1B", "CD14", "FCGR3A", "CD4", "CD8A", "CD3D"), k = 5, plot_km_elbow = F, exp_color_min = -2, exp_color_max = 2)
```
![image](https://user-images.githubusercontent.com/38284410/148064973-11af8caa-1517-40d1-80b3-5d4821863b9f.png)

Working on resolving this but not 100% as of right now where the issue is coming from.

**Comment by samuel-marsh** [comment] 2022-01-04 14:08
@crazyhottommy ok the kmeans elbow error is now fixed in develop branch (v0.6.3.0013).

- If length(features) > 21 and `elbow_kmax = NULL` then elbow_kmax will be set to 20.
- If length(features) < 21 and `elbow_kmax = NULL` then elbow_kmax will be set to length(features) - 1.
- If `elbow_kmax` is not NULL but value is greater than length(features) - 1 then warning will be printed and value will be changed to length(features) - 1.

Should solve all those issues.  Tested it with couple variations including:
```
Clustered_DotPlot(seurat_object = pbmc, features = c("IL1B", "CD14", "FCGR3A", "CD4", "CD8A", "CD3D"), k = 5)
```
Let me know if issue persists with your own data though!


Color scale fix in progress but for now if you set min and max based on quantiles of your data it should adjust correctly.

**Comment by samuel-marsh** [comment] 2022-01-04 14:11
As another note I also implemented a check for unique features in the function.  So helps out not needing: `features = unique(myeloid_features)` anymore.  It will simply print a message to let you know duplicate features were found and removed.

Also recently updated `Extract_Top_Markers` to include optional `make_unique` parameter when returning a vector.

**Comment by crazyhottommy** [comment] 2022-01-04 15:43
great! yeah, I was using `unique(myeloid_features)`

**Comment by samuel-marsh** [comment] 2022-01-04 15:57
Also new param when plotting smaller number of genes to allow for custom setting row label fontsize:
`row_label_size` (v0.6.3.0014)

**Comment by samuel-marsh** [comment] 2022-01-04 20:52
@crazyhottommy maybe you can give me your thoughts on color scale issue because I'm getting a little confused.  I think it must be something in ComplexHeatmap...  Feel like it is probably something simple/obvious but still learning ComplexHeatmap so probably just missing it.  Here's two examples one using full range of data and one where we force Seurat to restrict the data.  However, the end plots look the same with scale way beyond the min/max of data...

Expression scale color scheme is set (where the min and max are set to -2.5/2.5 by default):
https://github.com/samuel-marsh/scCustomize/blob/7ac2eb779388e7f0df8f48684017e1aa93e800d1/R/Seurat_Plotting.R#L1166


For this example we can control what the min and max values are using `col.min` and `col.max` when pulling data from Seurat (via the created plot).

**Set values to NULL**
```
seurat_plot <- DotPlot(object = seurat_object, features = features_unique, assay = assay, group.by = group.by, scale = TRUE, idents = idents, col.min = NULL, col.max = NULL)

data <- seurat_plot$data

max(data$avg.exp.scaled)
[1] 2.666666
min(datas$avg.exp.scaled)
[1] -1.153383
```


And resulting Clustered plotting function looks like this:
![image](https://user-images.githubusercontent.com/38284410/148120729-efeb8a48-667e-4ea9-af65-afec8472bec4.png)

**Force values to -1/1**
```
seurat_plot <- DotPlot(object = seurat_object, features = features_unique, assay = assay, group.by = group.by, scale = TRUE, idents = idents, col.min = -1, col.max = 1)

data <- seurat_plot$data

max(data$avg.exp.scaled)
[1] 1
min(data$avg.exp.scaled)
[1] -1
```

If we keep defaults in Clustered plotting function the plot still looks like:
![image](https://user-images.githubusercontent.com/38284410/148121886-a40bd24f-fc13-4d72-a2af-8b25aa012808.png)

**Comment by crazyhottommy** [comment] 2022-01-04 21:09
Hi, we should not force values by `col.min = -1, col.max = 1`
colorRamp2() is mapping the colors to values and any values that are out of the range will be mapped to yellow or blue.


>>> In following example, values between -2 and 2 are linearly interpolated to get corresponding colors, values larger than 2 are all mapped to red and values less than -2 are all mapped to green.

library(circlize)
col_fun = colorRamp2(c(-2, 0, 2), c("green", "white", "red"))
col_fun(seq(-3, 3))


see https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#colors

**Comment by samuel-marsh** [comment] 2022-01-04 22:08
Right, that was just example.  But in first scenario the min and max values are 2.666666 to -1.153383 and 

col_fun is effectively equal to:
```
col_fun = colorRamp2(c(-2.5, 0, 2.5), viridis::plasma(n = 30)[c(1,15, 30)])
```

so it should cap the values above 2.5 and the lower limit is below lower limit of data.  However the plot renders the scale at -4 to 4

![image](https://user-images.githubusercontent.com/38284410/148130407-168cc9c4-01cc-48cc-b9ec-165bb1ceed15.png)

**Comment by crazyhottommy** [comment] 2022-01-05 02:58
default is

```
exp_color_min = -2.5,
exp_color_middle = NULL,
exp_color_max = 2.5,
```
https://github.com/samuel-marsh/scCustomize/blob/develop/R/Seurat_Plotting.R#L1166

so it should be -2.5 to 2.5 by default? if I change exp_color_min = -4, exp_color_max = 4, the plot does look different (as expected)

**Comment by samuel-marsh** [comment] 2022-01-05 14:31
Ahh I think I see the issue.  With default settings (i.e. -2.5, 2.5) while the legend displays scale from -4 to 4 the color on the scale from 2.5 to 4 and -2.5 to -4 is actually the same.  Which is why when you change the parameters to be -4 to 4 the plot is different.  So issue appears to be be with way legend is being displayed not how the min/max colors are being set.  

Will dig into it some more...

**Comment by samuel-marsh** [comment] 2022-01-06 15:39
Ok updated default exp min/max values and updated function to ensure it pulls full dataset from Seurat and use ComplexHeatmap to set cutoffs and not Seurat.  Also added couple new error checks.

Dev version 0.6.3.0016.

Gonna close this issue but let me know if any new issues crop up.  Will likely merge and push full release tomorrow or early next week when I have time to update vignettes/website. :)

**Closed by samuel-marsh** 2022-01-06 15:39 UTC
Labels: bug

**Comment by samuel-marsh** [comment] 2022-01-10 18:32
@crazyhottommy version 0.7.0 now released and contains Clustered_DotPlot.  Still working on domino plot addition but basic version is good to go :).

**Comment by crazyhottommy** [comment] 2022-01-10 20:10
great work! thanks
