### ISSUE TITLE
functions appear to not follow the same coloring scheme

### ISSUE THREAD

**Issue by osmansharifi** [samuel-marsh/scCustomize#30] opened 2022-03-28 23:08 UTC
I used DimPlot_scCustom and Clustered_Dotplot, to visualize the cell types and markers respectively in my dataset. The two functions do not appear to follow the same color scheme order. For example, the color of astrocytes in the umap is gray and in the clustered dot plot it's magenta. It would be nice to coordinate the cell-type colors across all functions. 

Thank you

**Comment by samuel-marsh** [comment] 2022-03-28 23:17
Oh good find!!  I’m in the process of fixing how colors are provided to `Clustered_DotPlot` due to how complexHeatmap works with it (#29).  I’ll work this fix into that too.  Will update here when fixed in dev branch.

Thanks!
Sam

**Comment by osmansharifi** [comment] 2022-03-29 21:50
Awesome! Thank you, Would it be possible to post the color palette so users can follow the same coloring scheme for other custom plots ?

**Comment by samuel-marsh** [comment] 2022-03-29 22:09
So they are all using same palette but the issue is the order of identities provided to `Clustered_DotPlot` is different so things get moved into different order.

Most functions in scCustomize use an internal function which then uses forward facing `DiscretePalette_scCustomize` to set color palettes.  If less than 36 colors it uses polychrome palette and if more it uses varibow with `shuffle = TRUE`

https://github.com/samuel-marsh/scCustomize/blob/8414d1f5fb32277855b0619191a568932b7baeb0/R/Color_Palettes.R#L469-L485

**Comment by samuel-marsh** [comment] 2022-03-29 22:35
https://samuel-marsh.github.io/scCustomize/articles/Color_Palettes.html#large-discrete-palettes

**Comment by osmansharifi** [comment] 2022-03-30 22:22
Awesome! Thank you

**Comment by samuel-marsh** [comment] 2022-03-31 13:05
Hey @osmansharifi,

So been looking into this and wondering if you can send me reproducible example of this happening.  If not with a public SeuratData object then maybe with downsampled version of your own if you are able to share privately (shoot me email).  I was playing around and when I plot with pbmc3k dataset I get the same colors for each identity albeit with different order of identities top to bottom in the legend.  Here is my example using dev branch v0.7.0.0021.

Thanks, 
Sam

```
library(tidyverse)
library(Seurat)
library(scCustomize)

pbmc <- pbmc3k.SeuratData::pbmc3k.final
pbmc <- UpdateSeuratObject(pbmc)

DimPlot_scCustom(pbmc)
Clustered_DotPlot(pbmc, features = c("IL1B", "CD14", "FCGR3A", "CD4", "CD8A", "CD3D"), plot_km_elbow = F)
```

![image](https://user-images.githubusercontent.com/38284410/161061202-0a92fac2-80b7-445d-a0f4-072e95efc6f9.png)


![image](https://user-images.githubusercontent.com/38284410/161061180-1e0643e6-3777-4153-969c-117b414dfb6e.png)

**Comment by osmansharifi** [comment] 2022-04-05 23:06
Hi Sam, 

My apologies for the late response. Thank you for providing the color palette! I reinstalled scCustomize and it seems to have fixed the color coordination across functions. Thank you for looking into it. 

Best,
Osman

**Comment by samuel-marsh** [comment] 2022-04-05 23:43
Hi Osman,

no worries!!  Glad everything working well now!

Best,
Sam

**Closed by samuel-marsh** 2022-04-05 23:43 UTC
Labels: bug, more-info-needed
